// Admin-only: generate a fresh temporary password for a user and return a
// copy-able sign-in link. Used by the User Management panel so admins can
// hand-deliver credentials when the welcome email never arrives (Outlook
// suppression, typo, deleted message, etc.). Mirrors the credential rotation
// that admin-employee-magic-link / admin-resend-welcome-email perform, but
// does NOT send an email — the admin shares the link/password directly.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(value: unknown, status = 200) {
  return new Response(JSON.stringify(value), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function generateTempPassword(len = 14) {
  const bytes = new Uint8Array(len);
  crypto.getRandomValues(bytes);
  const alphabet = "ABCDEFGHJKMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789!@#$%";
  return Array.from(bytes).map((b) => alphabet[b % alphabet.length]).join("");
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

  const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
  const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const ANON = Deno.env.get("SUPABASE_ANON_KEY")!;

  const token = (req.headers.get("Authorization") ?? "").replace(/^Bearer\s+/i, "");
  if (!token) return json({ error: "Missing bearer token" }, 401);

  const userClient = createClient(SUPABASE_URL, ANON, {
    global: { headers: { Authorization: `Bearer ${token}` } },
  });
  const { data: userData, error: userErr } = await userClient.auth.getUser();
  if (userErr || !userData.user) return json({ error: "Invalid session" }, 401);
  const callerId = userData.user.id;

  const admin = createClient(SUPABASE_URL, SERVICE_ROLE);
  const { data: isAdmin } = await admin.rpc("has_role", { _user_id: callerId, _role: "admin" });
  const { data: isHrAdmin } = await admin.rpc("has_role", { _user_id: callerId, _role: "hr_admin" });
  if (!isAdmin && !isHrAdmin) return json({ error: "Admin access required" }, 403);

  const body = await req.json().catch(() => ({}));
  const userId: string = typeof body.userId === "string" ? body.userId : "";
  const emailIn: string = typeof body.email === "string" ? body.email.trim().toLowerCase() : "";
  const siteUrl: string = typeof body.siteUrl === "string" && body.siteUrl.startsWith("http")
    ? body.siteUrl.replace(/\/$/, "")
    : "https://blossom.abacommandcenter.com";

  if (!userId) return json({ error: "userId is required" }, 400);

  // Resolve email from the auth user if not provided.
  const { data: existing, error: getErr } = await admin.auth.admin.getUserById(userId);
  if (getErr || !existing?.user) return json({ error: getErr?.message ?? "User not found" }, 404);
  const email = (emailIn || existing.user.email || "").toLowerCase();
  if (!email) return json({ error: "User has no email on file" }, 400);

  // If admin provided a different email, sync it onto the auth user so the
  // sign-in link they share actually matches the login record.
  if (emailIn && emailIn !== (existing.user.email ?? "").toLowerCase()) {
    const { error: emailErr } = await admin.auth.admin.updateUserById(userId, {
      email,
      email_confirm: true,
    });
    if (emailErr) return json({ error: `Could not sync login email: ${emailErr.message}` }, 400);
  }

  const tempPassword = generateTempPassword();
  const { error: pwErr } = await admin.auth.admin.updateUserById(userId, {
    password: tempPassword,
    email_confirm: true,
  });
  if (pwErr) return json({ error: `Could not reset password: ${pwErr.message}` }, 400);

  // Force a password reset on first sign-in.
  await admin.from("profiles").update({ must_change_password: true }).eq("user_id", userId);

  const loginUrl = `${siteUrl}/auth?email=${encodeURIComponent(email)}&welcome=1`;

  // Audit trail so we can see who minted an invite link and when.
  try {
    await admin.from("invite_email_logs").insert({
      recipient_email: email,
      status: "manual_link",
      error_message: "Invite link generated by admin (no email sent)",
      roles: [],
      invited_user_id: userId,
      created_by: callerId,
    });
  } catch (_) { /* non-fatal */ }

  console.log("[invite-link] generated", { userId, email, by: callerId });

  return json({ ok: true, loginUrl, email, tempPassword });
});