// AUTO-GENERATED from parent-communication template spec. Do not hand-edit templates.
export interface ParentCommTemplate {
  id: string;
  title: string;
  section: string;
  stage: string;
  team: string;
  channel: string;
  useWhen: string;
  sms: string;
  subject: string;
  body: string;
  after: string;
}
export interface ParentCommInternalNote {
  id: string;
  title: string;
  body: string;
}

export const PARENT_COMM_TEMPLATES: ParentCommTemplate[] = [
  {
    "id": "1.01",
    "title": "New Inquiry Received - Warm Welcome",
    "section": "NEW LEAD / FIRST RESPONSE",
    "stage": "New Lead",
    "team": "Intake / Marketing",
    "channel": "SMS + Email",
    "useWhen": "A parent submits a website, Facebook, referral, phone, or other lead and Blossom is reaching out for the first time.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "1.02",
    "title": "First Call Attempt - No Answer",
    "section": "NEW LEAD / FIRST RESPONSE",
    "stage": "New Lead",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Intake calls a new parent lead and they do not answer.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "1.03",
    "title": "Second Follow-Up Attempt",
    "section": "NEW LEAD / FIRST RESPONSE",
    "stage": "New Lead",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Parent has not responded after first outreach.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "1.04",
    "title": "Final Outreach Before Can't Reach",
    "section": "NEW LEAD / FIRST RESPONSE",
    "stage": "New Lead / Can't Reach",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Parent has not responded after the required contact cadence.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "1.05",
    "title": "Reopened Lead",
    "section": "NEW LEAD / FIRST RESPONSE",
    "stage": "Reopened Lead",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "A parent responds after being marked Can't Reach or inactive.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "2.01",
    "title": "After-Hours AI Call Follow-Up - New Family",
    "section": "AFTER-HOURS AI / MISSED CALL FOLLOW-UP",
    "stage": "After-Hours / Overflow Call",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Retell AI answered a new family call after hours or when the team was unavailable.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "2.02",
    "title": "After-Hours AI Call Follow-Up - Existing Family",
    "section": "AFTER-HOURS AI / MISSED CALL FOLLOW-UP",
    "stage": "After-Hours / Existing Family",
    "team": "Intake / State Ops / Scheduling / Clinical depending on issue",
    "channel": "SMS + Email",
    "useWhen": "Existing family called after hours and needs routing.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "2.03",
    "title": "Missed Call During Business Hours",
    "section": "AFTER-HOURS AI / MISSED CALL FOLLOW-UP",
    "stage": "Missed Call",
    "team": "Intake / Scheduling / State Ops",
    "channel": "SMS",
    "useWhen": "A parent called during business hours and team missed the call.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "3.01",
    "title": "Schedule Intake Call",
    "section": "INTAKE CALL SCHEDULING AND CONFIRMATION",
    "stage": "Intake",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Parent needs to schedule intake call.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "3.02",
    "title": "Intake Call Confirmation",
    "section": "INTAKE CALL SCHEDULING AND CONFIRMATION",
    "stage": "Intake",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Intake call is scheduled.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "3.03",
    "title": "Intake Call Reminder",
    "section": "INTAKE CALL SCHEDULING AND CONFIRMATION",
    "stage": "Intake",
    "team": "Intake",
    "channel": "SMS",
    "useWhen": "Reminder before intake call.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "3.04",
    "title": "Missed Intake Call",
    "section": "INTAKE CALL SCHEDULING AND CONFIRMATION",
    "stage": "Intake",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Parent misses scheduled intake call.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "4.01",
    "title": "Send Initial Forms",
    "section": "FORMS, CONSENTS, AND DOCUMENT COLLECTION",
    "stage": "Forms",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Sending initial intake packet/forms.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "4.02",
    "title": "Forms Reminder",
    "section": "FORMS, CONSENTS, AND DOCUMENT COLLECTION",
    "stage": "Forms",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Forms are not completed.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "4.03",
    "title": "Forms Received",
    "section": "FORMS, CONSENTS, AND DOCUMENT COLLECTION",
    "stage": "Forms",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Forms are completed/received.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "4.04",
    "title": "Missing Documents Request",
    "section": "FORMS, CONSENTS, AND DOCUMENT COLLECTION",
    "stage": "Missing Information",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Specific documents/items are missing.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "4.05",
    "title": "Need Diagnosis Documentation",
    "section": "FORMS, CONSENTS, AND DOCUMENT COLLECTION",
    "stage": "Missing Diagnosis",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Diagnosis documentation is needed.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "4.06",
    "title": "Insurance Card Request",
    "section": "FORMS, CONSENTS, AND DOCUMENT COLLECTION",
    "stage": "Insurance Collection",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Parent needs to provide insurance card.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "4.07",
    "title": "Consent Forms Needed",
    "section": "FORMS, CONSENTS, AND DOCUMENT COLLECTION",
    "stage": "Consent",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Consent forms are missing or incomplete.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "5.01",
    "title": "Benefits Review Started",
    "section": "INSURANCE, BENEFITS, VOB, AND FINANCIAL REVIEW",
    "stage": "Benefits / VOB",
    "team": "Intake / RCM / Benefits",
    "channel": "SMS + Email",
    "useWhen": "Benefits/VOB review is being started.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "5.02",
    "title": "Benefits Review Pending",
    "section": "INSURANCE, BENEFITS, VOB, AND FINANCIAL REVIEW",
    "stage": "Benefits / VOB",
    "team": "RCM / Intake",
    "channel": "SMS + Email",
    "useWhen": "Benefits review is still pending.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "5.03",
    "title": "More Insurance Information Needed",
    "section": "INSURANCE, BENEFITS, VOB, AND FINANCIAL REVIEW",
    "stage": "Benefits / VOB",
    "team": "RCM / Intake",
    "channel": "SMS + Email",
    "useWhen": "Benefits team needs more information.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "5.04",
    "title": "Out-of-Network / OON Conversation Needed",
    "section": "INSURANCE, BENEFITS, VOB, AND FINANCIAL REVIEW",
    "stage": "Benefits / OON",
    "team": "RCM / Intake",
    "channel": "Email preferred, SMS brief only",
    "useWhen": "Family needs a benefits/payment discussion. Do not include detailed financial information in SMS.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "5.05",
    "title": "No OON Benefits / Not Eligible Next Step",
    "section": "INSURANCE, BENEFITS, VOB, AND FINANCIAL REVIEW",
    "stage": "Benefits / Decision",
    "team": "RCM / Intake",
    "channel": "Email preferred",
    "useWhen": "Benefits review creates a barrier and family needs next-step discussion.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "5.06",
    "title": "Payment Plan Discussion Needed",
    "section": "INSURANCE, BENEFITS, VOB, AND FINANCIAL REVIEW",
    "stage": "Benefits / Payment Plan",
    "team": "RCM / Finance",
    "channel": "Email preferred",
    "useWhen": "Family may need payment plan discussion.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "5.07",
    "title": "Credit Card / Payment Method Needed",
    "section": "INSURANCE, BENEFITS, VOB, AND FINANCIAL REVIEW",
    "stage": "Finance / Payment",
    "team": "Finance / RCM",
    "channel": "Email preferred",
    "useWhen": "Payment method is needed. Do not request full card details by SMS/email if secure process exists.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "6.01",
    "title": "Authorization Submission Started",
    "section": "AUTHORIZATIONS",
    "stage": "Authorizations",
    "team": "Authorizations",
    "channel": "SMS + Email",
    "useWhen": "Authorization submission process begins.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "6.02",
    "title": "Authorization Pending",
    "section": "AUTHORIZATIONS",
    "stage": "Authorizations",
    "team": "Authorizations",
    "channel": "SMS + Email",
    "useWhen": "Authorization is pending.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "6.03",
    "title": "Authorization Approved",
    "section": "AUTHORIZATIONS",
    "stage": "Authorizations",
    "team": "Authorizations / Scheduling / Staffing",
    "channel": "SMS + Email",
    "useWhen": "Authorization is approved and next steps begin.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "6.04",
    "title": "Authorization Needs Additional Information",
    "section": "AUTHORIZATIONS",
    "stage": "Authorizations",
    "team": "Authorizations",
    "channel": "SMS + Email",
    "useWhen": "Additional info is needed for auth.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "6.05",
    "title": "Authorization Denial / Discussion Needed",
    "section": "AUTHORIZATIONS",
    "stage": "Authorizations / Denial",
    "team": "Authorizations / Clinical / RCM",
    "channel": "Email preferred, SMS brief only",
    "useWhen": "Authorization was denied or requires careful discussion.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "7.01",
    "title": "Ready to Schedule Assessment",
    "section": "ASSESSMENT SCHEDULING",
    "stage": "Assessment Scheduling",
    "team": "Scheduling / Clinical / State Ops",
    "channel": "SMS + Email",
    "useWhen": "Child is ready for assessment scheduling.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "7.02",
    "title": "Assessment Scheduled Confirmation",
    "section": "ASSESSMENT SCHEDULING",
    "stage": "Assessment Scheduling",
    "team": "Scheduling / Clinical",
    "channel": "SMS + Email",
    "useWhen": "Assessment is scheduled.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "7.03",
    "title": "Assessment Reminder",
    "section": "ASSESSMENT SCHEDULING",
    "stage": "Assessment Scheduling",
    "team": "Scheduling",
    "channel": "SMS",
    "useWhen": "Reminder before assessment.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "7.04",
    "title": "Assessment Reschedule Needed",
    "section": "ASSESSMENT SCHEDULING",
    "stage": "Assessment Scheduling",
    "team": "Scheduling",
    "channel": "SMS + Email",
    "useWhen": "Assessment needs rescheduling.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "7.05",
    "title": "Assessment Completed / Next Steps",
    "section": "ASSESSMENT SCHEDULING",
    "stage": "Assessment Completed",
    "team": "Clinical / Scheduling / State Ops",
    "channel": "SMS + Email",
    "useWhen": "Assessment is completed and family needs next-step update.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "8.01",
    "title": "Availability Request",
    "section": "SCHEDULING, STAFFING, AND START OF SERVICES",
    "stage": "Scheduling",
    "team": "Scheduling / Staffing",
    "channel": "SMS + Email",
    "useWhen": "Need family availability for services.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "8.02",
    "title": "Schedule Proposal",
    "section": "SCHEDULING, STAFFING, AND START OF SERVICES",
    "stage": "Scheduling",
    "team": "Scheduling",
    "channel": "SMS + Email",
    "useWhen": "Proposing service schedule.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "8.03",
    "title": "Schedule Confirmed",
    "section": "SCHEDULING, STAFFING, AND START OF SERVICES",
    "stage": "Scheduling",
    "team": "Scheduling / Staffing",
    "channel": "SMS + Email",
    "useWhen": "Schedule is confirmed.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "8.04",
    "title": "Therapist / RBT Introduction",
    "section": "SCHEDULING, STAFFING, AND START OF SERVICES",
    "stage": "Staffing / Start Services",
    "team": "Staffing / State Ops",
    "channel": "SMS + Email",
    "useWhen": "Introducing assigned RBT/therapist.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "8.05",
    "title": "BCBA Introduction",
    "section": "SCHEDULING, STAFFING, AND START OF SERVICES",
    "stage": "Clinical / Start Services",
    "team": "Clinical / State Ops",
    "channel": "SMS + Email",
    "useWhen": "Introducing BCBA.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "8.06",
    "title": "First Session Confirmation",
    "section": "SCHEDULING, STAFFING, AND START OF SERVICES",
    "stage": "Start Services",
    "team": "Scheduling / Staffing / State Ops",
    "channel": "SMS + Email",
    "useWhen": "First 97153/session date is confirmed.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "8.07",
    "title": "Waiting on Staffing",
    "section": "SCHEDULING, STAFFING, AND START OF SERVICES",
    "stage": "Staffing",
    "team": "Staffing / State Ops",
    "channel": "SMS + Email",
    "useWhen": "Family is waiting for staffing match.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "8.08",
    "title": "Schedule Change Notice",
    "section": "SCHEDULING, STAFFING, AND START OF SERVICES",
    "stage": "Scheduling / Active Client",
    "team": "Scheduling",
    "channel": "SMS + Email",
    "useWhen": "Schedule changes.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "8.09",
    "title": "Provider Running Late",
    "section": "SCHEDULING, STAFFING, AND START OF SERVICES",
    "stage": "Active Client",
    "team": "Scheduling / Staffing / Clinical",
    "channel": "SMS",
    "useWhen": "Provider is late.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "8.10",
    "title": "Session Cancellation by Blossom",
    "section": "SCHEDULING, STAFFING, AND START OF SERVICES",
    "stage": "Active Client",
    "team": "Scheduling / Staffing",
    "channel": "SMS + Email",
    "useWhen": "Blossom must cancel/reschedule session.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "8.11",
    "title": "Family Cancellation Confirmation",
    "section": "SCHEDULING, STAFFING, AND START OF SERVICES",
    "stage": "Active Client",
    "team": "Scheduling",
    "channel": "SMS",
    "useWhen": "Parent cancels and team confirms.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "8.12",
    "title": "No-Show / Not Available",
    "section": "SCHEDULING, STAFFING, AND START OF SERVICES",
    "stage": "Active Client",
    "team": "Scheduling / State Ops",
    "channel": "SMS + Email",
    "useWhen": "Provider arrives or logs in and family is unavailable/no-show. Keep tone neutral.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "9.01",
    "title": "Parent Training Scheduling",
    "section": "CLINICAL / ACTIVE CLIENT COMMUNICATION",
    "stage": "Clinical / Active Client",
    "team": "Clinical / Case Manager",
    "channel": "SMS + Email",
    "useWhen": "Scheduling parent training.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "9.02",
    "title": "Clinical Meeting Reminder",
    "section": "CLINICAL / ACTIVE CLIENT COMMUNICATION",
    "stage": "Clinical / Active Client",
    "team": "Clinical / Case Manager",
    "channel": "SMS + Email",
    "useWhen": "Reminding parent of BCBA/case meeting.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "9.03",
    "title": "General Clinical Question Received",
    "section": "CLINICAL / ACTIVE CLIENT COMMUNICATION",
    "stage": "Clinical / Active Client",
    "team": "Clinical / Case Manager",
    "channel": "SMS + Email",
    "useWhen": "Parent asks clinical question and non-clinical team needs to route.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "9.04",
    "title": "Incident Follow-Up Acknowledgment",
    "section": "CLINICAL / ACTIVE CLIENT COMMUNICATION",
    "stage": "Clinical / Incident",
    "team": "Clinical / State Ops / QA",
    "channel": "Email preferred, SMS brief only",
    "useWhen": "Parent reports concern/incident. Do not include sensitive details in SMS.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "9.05",
    "title": "Services on Pause",
    "section": "CLINICAL / ACTIVE CLIENT COMMUNICATION",
    "stage": "Active Client / Pause",
    "team": "State Ops / Clinical / Scheduling",
    "channel": "SMS + Email",
    "useWhen": "Services are paused.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "9.06",
    "title": "Resume Services Discussion",
    "section": "CLINICAL / ACTIVE CLIENT COMMUNICATION",
    "stage": "Active Client / Resume Services",
    "team": "State Ops / Clinical / Scheduling",
    "channel": "SMS + Email",
    "useWhen": "Family may resume services.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "10.01",
    "title": "Concern Received - Warm Acknowledgment",
    "section": "COMPLAINTS, ESCALATIONS, AND FAMILY CONCERNS",
    "stage": "Concern / Escalation",
    "team": "Any Team / State Ops / Leadership",
    "channel": "SMS + Email",
    "useWhen": "Parent expresses concern and you need to acknowledge quickly.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "10.02",
    "title": "Escalation Owner Assigned",
    "section": "COMPLAINTS, ESCALATIONS, AND FAMILY CONCERNS",
    "stage": "Escalation",
    "team": "State Ops / Leadership",
    "channel": "SMS + Email",
    "useWhen": "Parent concern has assigned owner.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "10.03",
    "title": "We Are Reviewing This",
    "section": "COMPLAINTS, ESCALATIONS, AND FAMILY CONCERNS",
    "stage": "Escalation",
    "team": "State Ops / Leadership / QA",
    "channel": "SMS + Email",
    "useWhen": "Review is underway and parent needs update.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "10.04",
    "title": "Escalation Resolved / Close Loop",
    "section": "COMPLAINTS, ESCALATIONS, AND FAMILY CONCERNS",
    "stage": "Escalation Resolution",
    "team": "State Ops / Leadership",
    "channel": "Email preferred",
    "useWhen": "Issue is resolved or next step is confirmed.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "11.01",
    "title": "Referral Partner Thank You",
    "section": "MARKETING / REFERRALS / LIFETIME JOURNEY",
    "stage": "Referral",
    "team": "Marketing / Business Development / Intake",
    "channel": "Email",
    "useWhen": "Referral partner sends family.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "11.02",
    "title": "Parent Event Follow-Up",
    "section": "MARKETING / REFERRALS / LIFETIME JOURNEY",
    "stage": "Marketing / Event Lead",
    "team": "Marketing / Intake",
    "channel": "SMS + Email",
    "useWhen": "Parent met Blossom at event.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "11.03",
    "title": "Clinic Tour Invitation",
    "section": "MARKETING / REFERRALS / LIFETIME JOURNEY",
    "stage": "Marketing / Clinic Interest",
    "team": "Marketing / Clinic / State Ops",
    "channel": "SMS + Email",
    "useWhen": "Inviting parent to tour clinic.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "11.04",
    "title": "Referral Source Confirmation",
    "section": "MARKETING / REFERRALS / LIFETIME JOURNEY",
    "stage": "Marketing / Lifetime Journey",
    "team": "Marketing / Intake",
    "channel": "SMS + Email",
    "useWhen": "Need to confirm how parent heard about Blossom.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "12.01",
    "title": "Office Documents Received",
    "section": "GENERAL ADMIN / OFFICE / LOGISTICS",
    "stage": "Admin",
    "team": "Office / Intake / HR/Admin",
    "channel": "SMS + Email",
    "useWhen": "Parent sends documents.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "12.02",
    "title": "Need Updated Contact Information",
    "section": "GENERAL ADMIN / OFFICE / LOGISTICS",
    "stage": "Admin",
    "team": "Any Team",
    "channel": "SMS + Email",
    "useWhen": "Contact info is outdated or missing.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "12.03",
    "title": "Weather / Office Closure",
    "section": "GENERAL ADMIN / OFFICE / LOGISTICS",
    "stage": "Operations / Active Client",
    "team": "Operations / Scheduling / State Ops",
    "channel": "SMS + Email",
    "useWhen": "Weather or closure affects services.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "12.04",
    "title": "Holiday Reminder",
    "section": "GENERAL ADMIN / OFFICE / LOGISTICS",
    "stage": "Operations / Active Client",
    "team": "Scheduling / Operations",
    "channel": "SMS + Email",
    "useWhen": "Holiday schedule affects services.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "13.01",
    "title": "Parent Requested Discharge / Pause Acknowledgment",
    "section": "DISCHARGE, CLOSURE, AND INACTIVE",
    "stage": "Discharge / Pause",
    "team": "State Ops / Clinical",
    "channel": "Email preferred, SMS brief only",
    "useWhen": "Parent requests discharge or pause.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "13.02",
    "title": "Inactive Lead Closure",
    "section": "DISCHARGE, CLOSURE, AND INACTIVE",
    "stage": "Inactive Lead",
    "team": "Intake",
    "channel": "SMS + Email",
    "useWhen": "Lead is being closed/inactivated after no movement.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "13.03",
    "title": "Services Ending Confirmation",
    "section": "DISCHARGE, CLOSURE, AND INACTIVE",
    "stage": "Discharge",
    "team": "Clinical / State Ops",
    "channel": "Email",
    "useWhen": "Services are ending and needs formal confirmation.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "14.01",
    "title": "Family Feedback Request",
    "section": "SURVEYS, QA, AND FEEDBACK",
    "stage": "QA / Feedback",
    "team": "QA / State Ops / Leadership",
    "channel": "SMS + Email",
    "useWhen": "Asking family for feedback.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "14.02",
    "title": "Satisfaction Survey",
    "section": "SURVEYS, QA, AND FEEDBACK",
    "stage": "QA / Feedback",
    "team": "QA / Operations",
    "channel": "SMS + Email",
    "useWhen": "Sending survey link.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "14.03",
    "title": "Positive Feedback Thank You",
    "section": "SURVEYS, QA, AND FEEDBACK",
    "stage": "QA / Feedback",
    "team": "QA / Leadership / Marketing",
    "channel": "SMS + Email",
    "useWhen": "Parent gives positive feedback.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  },
  {
    "id": "14.04",
    "title": "Permission to Use Testimonial",
    "section": "SURVEYS, QA, AND FEEDBACK",
    "stage": "Marketing / Feedback",
    "team": "Marketing",
    "channel": "Email",
    "useWhen": "Asking parent permission to use testimonial.",
    "sms": "",
    "subject": "",
    "body": "",
    "after": ""
  }
];

export const PARENT_COMM_INTERNAL_NOTES: ParentCommInternalNote[] = [
  {
    "id": "15.01",
    "title": "Parent Contact Attempt",
    "body": "Template:\r\nContacted parent via {{channel}} on {{date_time}}. Outcome: {{outcome}}. Next action: {{next_step}}. Follow-up date: {{deadline_date}}. Owner: {{team_member_full_name}}."
  },
  {
    "id": "15.02",
    "title": "Parent Reached",
    "body": "Template:\r\nSpoke with {{parent_first_name}} on {{date_time}}. Summary: {{summary}}. Parent needs: {{parent_needs}}. Blossom next step: {{next_step}}. Owner: {{team_member_full_name}}. Follow-up date: {{deadline_date}}."
  },
  {
    "id": "15.03",
    "title": "Missing Information",
    "body": "Template:\r\nMissing items requested from parent: {{missing_items}}. Request sent via {{channel}} on {{date_time}}. Follow-up due: {{deadline_date}}. Do not move forward until resolved unless manager approves exception."
  },
  {
    "id": "15.04",
    "title": "Escalation Routed",
    "body": "Template:\r\nParent concern/escalation routed to {{owner_name}} on {{date_time}}. Issue summary: {{summary}}. Parent was told: {{parent_message_summary}}. Next update due: {{deadline_date}}."
  },
  {
    "id": "15.05",
    "title": "Handoff to Next Department",
    "body": "Template:\r\nHandoff sent to {{department}} / {{owner_name}}. Reason: {{reason}}. Required action: {{next_step}}. Supporting info complete: {{yes_no}}. Follow-up date: {{deadline_date}}."
  }
];

export const PARENT_COMM_SECTIONS = Array.from(new Set(PARENT_COMM_TEMPLATES.map(t => t.section)));
export const PARENT_COMM_TEAMS = Array.from(new Set(PARENT_COMM_TEMPLATES.flatMap(t => t.team.split('/').map(s => s.trim())).filter(Boolean))).sort();
export const PARENT_COMM_CHANNELS = Array.from(new Set(PARENT_COMM_TEMPLATES.map(t => t.channel))).sort();

export const PARENT_COMM_MERGE_FIELDS = [
  'parent_first_name','parent_full_name','child_first_name','state',
  'team_member_first_name','team_member_full_name','team_member_title',
  'team_member_phone','team_member_email','state_director_name',
  'intake_coordinator_name','scheduling_contact_name','staffing_contact_name',
  'bcba_name','rbt_name','clinic_name','clinic_address','appointment_date',
  'appointment_time','call_back_number','forms_link','pandadoc_link','upload_link',
  'calendar_link','insurance_name','missing_items','authorization_status',
  'start_date','schedule_summary','next_step','deadline_date','office_email',
  'office_phone','after_hours_note',
];
