/**
 * Blossom OS — Integration registry.
 *
 * Single source of truth for the systems Blossom ABA Therapy actually
 * runs against. Admin > Integrations and any future integration health
 * dashboards should read from here instead of inlining their own list.
 *
 * Notes:
 *  - Static `status` values in this registry describe the intended
 *    integration state (configured / planned / maybe / disabled), NOT
 *    proof of a live backend connection. The Integrations UI overlays
 *    live `integration_connections` rows on top of these entries; the
 *    card only shows "Connected" when a real backend row confirms it.
 *  - CentralReach remains the clinical EMR; Blossom OS connects to it.
 *  - Viventium is the HRIS / employee-lifecycle source and governs
 *    Blossom OS user activation/deactivation reviews.
 *  - PandaDoc is an e-signature / document execution integration —
 *    NOT the source of truth for patients, HR, or clinical data.
 *  - "Solom / Solum" — display label is intentionally flexible until the
 *    final vendor spelling is confirmed. The canonical id stays `solum`
 *    so existing references keep working.
 */

import type {
  BlossomIntegration,
  IntegrationSyncRun,
} from "./types";

export const BLOSSOM_INTEGRATIONS: BlossomIntegration[] = [
  {
    id: "centralreach",
    name: "CentralReach",
    displayName: "CentralReach",
    category: "clinical_emr",
    ownerDepartment: "Clinical Operations / Operations Leadership",
    criticality: "critical",
    status: "configured",
    methods: ["api", "file_import"],
    inboundData: [
      "Clients",
      "Clinical team assignments",
      "BCBA/RBT pairings",
      "Schedules",
      "Authorizations",
      "Sessions",
      "Cancellations",
      "Supervision & parent training signals",
      "Service delivery / billing export",
    ],
    outboundData: ["Operational status flags", "Task escalations"],
    dependentModules: [
      "Clinical Dashboard",
      "BCBA Dashboard",
      "Case Manager",
      "RBT",
      "Scheduling",
      "Staffing",
      "Authorizations",
      "QA",
      "Reports",
      "Operations Command Center",
      "Patient Lifetime Journey",
    ],
    sourceOfTruthFor: [
      "Clinical EMR",
      "Billing",
      "Clinical scheduling",
      "Authorizations",
    ],
    notes:
      "CentralReach is the ongoing EMR. Blossom OS connects to it through API/import — it is not being replaced.",
  },
  {
    id: "viventium",
    name: "Viventium",
    displayName: "Viventium",
    category: "hris",
    ownerDepartment: "HR Team",
    criticality: "critical",
    status: "configured",
    methods: ["api", "file_import"],
    inboundData: [
      "Employee status",
      "Hire date",
      "Termination / inactive status",
      "Payroll & onboarding paperwork status",
      "Department / role",
    ],
    outboundData: ["Access review triggers", "Onboarding readiness signals"],
    dependentModules: [
      "User Management",
      "Employee Directory",
      "HR Dashboard",
      "Recruiting Onboarding Handoff",
      "Role Management",
      "NFC Badge Management",
      "User Logins Vault governance",
    ],
    sourceOfTruthFor: ["Employee lifecycle", "Payroll", "Hire/termination dates"],
    notes:
      "Viventium governs employee lifecycle. Blossom OS should use Viventium status to drive user activation, deactivation, and access reviews.",
  },
  {
    id: "apploi",
    name: "Apploi",
    displayName: "Apploi",
    category: "recruiting",
    ownerDepartment: "Recruiting Team / HR Team",
    criticality: "critical",
    status: "configured",
    methods: ["api"],
    inboundData: [
      "Candidates",
      "Applications",
      "Interview status",
      "Offer status",
      "Candidate source",
    ],
    outboundData: ["Onboarding handoff status"],
    dependentModules: [
      "Recruiting Dashboard",
      "Candidate Pipeline",
      "Interview Scheduling",
      "Offer Tracker",
      "Onboarding Handoff",
      "HR Dashboard",
    ],
    sourceOfTruthFor: ["Applicant tracking", "Recruiting pipeline"],
    notes: "ATS for RBT/BCBA recruiting; handoff to Viventium on hire.",
  },
  {
    id: "ms365",
    name: "Microsoft 365",
    displayName: "Microsoft Outlook / Microsoft 365",
    category: "communications",
    ownerDepartment: "Operations / All Departments",
    criticality: "critical",
    status: "configured",
    methods: ["oauth", "api"],
    inboundData: [
      "Email activity",
      "Calendar events",
      "Interview scheduling",
      "Internal communication activity",
    ],
    outboundData: ["Calendar invites", "Outbound email"],
    dependentModules: [
      "Communications",
      "Patient Lifetime Journey",
      "Recruiting Interviews",
      "Intake Parent Communication",
      "Case Manager Family Communication",
      "User Activity Log",
      "Patient Activity Log",
    ],
    sourceOfTruthFor: ["Email", "Internal calendar"],
    notes: "Powers email/calendar surfaces across Blossom OS.",
  },
  {
    id: "jivetel",
    name: "Jivetel",
    displayName: "Jivetel",
    category: "communications",
    ownerDepartment: "HR / Operations / Marketing (per line)",
    criticality: "standard",
    status: "configured",
    methods: ["api"],
    inboundData: [
      "Phone users",
      "Extensions",
      "Call routing",
      "Shared lines",
      "Employee phone activity",
    ],
    outboundData: ["Phone provisioning requests"],
    dependentModules: [
      "Phone System",
      "Shared Lines",
      "Phone Requests",
      "Directory",
      "User Activity Log",
    ],
    sourceOfTruthFor: ["Phone system", "Extensions"],
    notes: "Office phone system for Blossom departments and shared lines.",
  },
  {
    id: "ctm",
    name: "CallTrackingMetrics",
    displayName: "CTM / CallTrackingMetrics",
    category: "marketing",
    ownerDepartment: "Marketing Team",
    criticality: "critical",
    status: "configured",
    methods: ["api", "webhook"],
    inboundData: [
      "Source-tracked inbound calls",
      "Call recordings",
      "Caller identity",
      "Campaign / source attribution",
    ],
    outboundData: ["Lead creation"],
    dependentModules: [
      "CTM / Call Tracking",
      "Marketing Dashboard",
      "Intake Dashboard",
      "Patient Lifetime Journey",
      "Communications",
    ],
    sourceOfTruthFor: ["Inbound call attribution"],
    notes: "Critical for lead attribution and patient journey call events.",
  },
  {
    id: "retell",
    name: "Retell AI",
    displayName: "Retell AI",
    category: "ai_voice",
    ownerDepartment: "Marketing / Intake / Operations",
    criticality: "standard",
    status: "configured",
    methods: ["webhook", "api"],
    inboundData: [
      "After-hours calls",
      "Caller summaries",
      "Extracted lead data",
      "Department routing",
    ],
    outboundData: ["Follow-up tasks"],
    dependentModules: [
      "After-Hours Calls",
      "Call Email Audit",
      "Intake Dashboard",
      "Patient Lifetime Journey",
      "Communications",
    ],
    sourceOfTruthFor: ["After-hours AI voice"],
    notes: "Already connected. Captures after-hours intake and routes follow-ups.",
  },
  {
    id: "leadtrap",
    name: "LeadTrap",
    displayName: "LeadTrap",
    category: "lead_capture",
    ownerDepartment: "Marketing Team / Intake",
    criticality: "standard",
    status: "configured",
    methods: ["webhook"],
    inboundData: [
      "Web leads",
      "Form submissions",
      "Lead metadata",
      "Source attribution",
    ],
    outboundData: [],
    dependentModules: [
      "LeadTrap",
      "Lead Sources",
      "Intake Dashboard",
      "Patient Lifetime Journey",
    ],
    sourceOfTruthFor: ["Web lead capture"],
    notes: "Captures web leads and routes them into Intake.",
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    displayName: "Mailchimp",
    category: "marketing",
    ownerDepartment: "Marketing Team",
    criticality: "standard",
    status: "configured",
    methods: ["api"],
    inboundData: [
      "Campaign performance",
      "Audience segments",
      "Lead nurture activity",
      "Email engagement",
    ],
    outboundData: ["Audience updates"],
    dependentModules: [
      "Marketing Dashboard",
      "Campaigns",
      "Patient Lifetime Journey",
      "Lead Sources",
      "Attribution & ROI",
    ],
    sourceOfTruthFor: ["Email marketing campaigns"],
    notes: "Marketing email + nurture activity feeding patient journey events.",
  },
  {
    id: "resend",
    name: "Resend",
    displayName: "Resend",
    category: "communications",
    ownerDepartment: "Operations / Platform",
    criticality: "critical",
    status: "configured",
    methods: ["api"],
    inboundData: [
      "Email delivery status",
      "Bounce / complaint signals",
    ],
    outboundData: [
      "Welcome / invite emails",
      "Email MFA codes",
      "Evaluation emails",
      "Transactional notifications",
    ],
    dependentModules: [
      "User Management invites",
      "Welcome emails",
      "Email MFA",
      "Evaluation emails",
    ],
    sourceOfTruthFor: ["Transactional email delivery"],
    notes:
      "Already in production for invite/welcome/MFA flows. Do not rebuild — Pass 1 only registers it as a first-class integration.",
  },
  {
    id: "make",
    name: "Make.com",
    displayName: "Make.com",
    category: "marketing",
    ownerDepartment: "Operations / Platform",
    criticality: "standard",
    status: "disabled",
    methods: ["webhook", "api"],
    internalOnly: true,
    inboundData: [
      "Automation bridge events",
      "Migration-era event payloads",
    ],
    outboundData: ["Outbound automation events"],
    dependentModules: [
      "Lead Sources",
      "Patient Lifetime Journey",
      "Operational automations",
    ],
    sourceOfTruthFor: [],
    notes:
      "Internal / legacy automation bridge only. Hidden from user-facing integration readiness surfaces. Blossom OS does not depend on Make.com for the operating system's readiness.",
  },
  {
    id: "google-ads",
    name: "Google Ads",
    displayName: "Google Ads",
    category: "marketing",
    ownerDepartment: "Marketing Team",
    criticality: "standard",
    status: "configured",
    methods: ["api"],
    inboundData: [
      "Campaign performance",
      "Conversion tracking",
      "Cost per lead",
      "Lead source attribution",
    ],
    outboundData: [],
    dependentModules: [
      "Google Ads",
      "Marketing Dashboard",
      "Lead Sources",
      "Attribution & ROI",
    ],
    sourceOfTruthFor: ["Paid search performance"],
    notes: "Paid search performance and conversion tracking.",
  },
  {
    id: "meta-ads",
    name: "Meta Ads",
    displayName: "Facebook Ads / Meta Ads",
    category: "marketing",
    ownerDepartment: "Marketing Team",
    criticality: "standard",
    status: "configured",
    methods: ["api"],
    inboundData: [
      "Campaign performance",
      "Form leads",
      "Cost per lead",
      "Creative attribution",
    ],
    outboundData: [],
    dependentModules: [
      "Facebook Ads",
      "Marketing Dashboard",
      "Lead Sources",
      "Attribution & ROI",
    ],
    sourceOfTruthFor: ["Paid social performance"],
    notes: "Paid social performance and lead-form capture.",
  },
  {
    id: "solum",
    name: "Solum",
    displayName: "Solom / Solum",
    category: "eligibility",
    ownerDepartment: "Intake / Authorizations",
    criticality: "maybe",
    status: "maybe",
    methods: ["api", "manual_upload"],
    inboundData: [
      "Verification of benefits",
      "Eligibility status",
      "VOB packet / status",
    ],
    outboundData: ["Intake stage movement"],
    dependentModules: [
      "Intake Dashboard",
      "Lead Benefits Cheat Sheets",
      "Missing Information",
      "Authorizations",
      "Patient Lifetime Journey",
    ],
    sourceOfTruthFor: ["VOB workflow"],
    notes:
      "Vendor spelling unconfirmed — display label flexes between Solom and Solum until finalized.",
  },
  {
    id: "eligipro",
    name: "Eligipro",
    displayName: "Eligipro",
    category: "eligibility",
    ownerDepartment: "Intake / Authorizations",
    criticality: "standard",
    status: "configured",
    methods: ["api"],
    inboundData: [
      "Eligibility checks",
      "Plan details",
      "Insurance validation",
      "OON / no benefit status",
    ],
    outboundData: [],
    dependentModules: [
      "Intake",
      "Authorizations",
      "Lead Benefits Cheat Sheets",
      "No OON Benefits",
      "Patient Lifetime Journey",
    ],
    sourceOfTruthFor: ["Real-time eligibility"],
    notes: "Real-time eligibility verification.",
  },
  {
    id: "pandadoc",
    name: "PandaDoc",
    displayName: "PandaDoc",
    category: "documents",
    ownerDepartment: "Intake / HR / Operations (per template)",
    criticality: "standard",
    status: "needs_attention",
    methods: ["api", "webhook"],
    inboundData: [
      "Template list",
      "Sent document status",
      "Signer status",
      "Completion status",
      "Signed document links",
    ],
    outboundData: ["Document send requests"],
    dependentModules: [
      "Intake",
      "Patient record",
      "HR onboarding",
      "Resource / Document management",
    ],
    sourceOfTruthFor: [],
    notes:
      "E-signature / document execution layer ONLY. Not the source of truth for patients, HR, or clinical data — abstracted so another e-sign provider could replace it.",
  },
  {
    id: "calendly",
    name: "Calendly",
    displayName: "Calendly",
    category: "meetings",
    ownerDepartment: "Recruiting / Intake / Business Development / Executives",
    criticality: "standard",
    status: "configured",
    methods: ["api", "embedded_link"],
    inboundData: [
      "Interview scheduling",
      "Consultation scheduling",
      "External partner meetings",
    ],
    outboundData: ["Booking links"],
    dependentModules: [
      "Recruiting Interviews",
      "Intake Parent Communication",
      "Business Development",
      "Account Settings / booking links",
    ],
    sourceOfTruthFor: ["External booking links"],
    notes: "External-facing scheduling for interviews and consults.",
  },
  {
    id: "fathom",
    name: "Fathom AI",
    displayName: "Fathom AI",
    category: "meetings",
    ownerDepartment: "Leadership / Operations",
    criticality: "maybe",
    status: "maybe",
    methods: ["api"],
    inboundData: [
      "Meeting summaries",
      "Internal decision capture",
      "Follow-up tasks",
      "Leadership meeting outcomes",
    ],
    outboundData: [],
    dependentModules: [
      "BloomGrowth / L10 meeting follow-ups",
      "Operations Command Center",
      "Department Scorecards",
      "User Activity Log",
    ],
    sourceOfTruthFor: ["Meeting transcripts / summaries"],
    notes: "AI meeting notes — pending decision on full rollout.",
  },
  {
    id: "bloomgrowth",
    name: "BloomGrowth",
    displayName: "BloomGrowth",
    category: "meetings",
    ownerDepartment: "Executive Leadership / Operations Leadership",
    criticality: "standard",
    status: "configured",
    methods: ["api", "embedded_link"],
    inboundData: [
      "L10 meetings",
      "Rocks / goals",
      "Issues list",
      "To-dos",
      "Meeting decisions",
    ],
    outboundData: [],
    dependentModules: [
      "Executive Dashboard",
      "Operations Dashboard",
      "Department Scorecards",
      "Leadership Accountability",
      "User Activity Log",
    ],
    sourceOfTruthFor: ["L10 meeting cadence"],
    notes: "Leadership meeting operating system (EOS / L10).",
  },
  {
    id: "go-integrate-nava",
    name: "Go Integrate Nava",
    displayName: "Go Integrate Nava",
    category: "eligibility",
    ownerDepartment: "Intake / Authorizations / Operations",
    criticality: "standard",
    status: "not_configured",
    methods: ["planned"],
    inboundData: [],
    outboundData: [],
    dependentModules: [],
    sourceOfTruthFor: [],
    notes:
      "Vendor details pending confirmation. Added as a required integration placeholder so Blossom OS has a backend-ready connection record once credentials and API documentation are available.",
  },
];

/** Lookup helper. */
export function getIntegration(id: string): BlossomIntegration | undefined {
  return BLOSSOM_INTEGRATIONS.find((i) => i.id === id);
}

/**
 * Placeholder sync-run log. Real sync history will replace this once the
 * adapters wire to live APIs; until then, pages can render this shape to
 * preview the integration health surface.
 */
export const MOCK_INTEGRATION_SYNC_RUNS: IntegrationSyncRun[] = [
  {
    id: "run-cr-001",
    integrationId: "centralreach",
    startedAt: new Date(Date.now() - 1000 * 60 * 7).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
    status: "success",
    recordsReceived: 312,
    recordsUpdated: 41,
    recordsCreated: 3,
  },
  {
    id: "run-viv-001",
    integrationId: "viventium",
    startedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 59).toISOString(),
    status: "success",
    recordsReceived: 184,
    recordsUpdated: 12,
    recordsCreated: 1,
  },
  {
    id: "run-pd-001",
    integrationId: "pandadoc",
    startedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 89).toISOString(),
    status: "failed",
    errorMessage: "Webhook signature mismatch — reauthorize.",
  },
];