ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'New Lead';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'In Contact';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Sent Form';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Missing Information';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Form Received';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Sent to VOB';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'VOB Pending';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'VOB Received';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Financial Review';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Payment Plan Required';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Payment Plan Received';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Approved for Services';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Not Qualified';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Converted to Client';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Initial Auth – Awaiting Submission';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Initial Auth – Submitted';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Initial Auth – Approved';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Waiting on Consent';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Assessment Completed';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Treatment Plan Pending';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'QA Review';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'QA Issues / Fix Required';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'QA Approved';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Treatment Auth – Awaiting Submission';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Treatment Auth – Submitted';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Treatment Auth – Approved';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Treatment Auth – Denied';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Matching in Progress';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'RBT Assigned';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Pending Schedule';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Schedule Created';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Reauth Triggered';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Progress Report Needed';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Progress Report Received';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Reauth Submitted';
ALTER TYPE public.client_stage ADD VALUE IF NOT EXISTS 'Reauth Approved';