CREATE OR REPLACE FUNCTION public.user_is_state_scoped_role()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT
       public.has_role(auth.uid(), 'state_director')
    OR public.has_role(auth.uid(), 'assistant_state_director')
    OR public.has_role(auth.uid(), 'intake')
    OR public.has_role(auth.uid(), 'intake_lead')
    OR public.has_role(auth.uid(), 'intake_coordinator')
    OR public.has_role(auth.uid(), 'auth_team')
    OR public.has_role(auth.uid(), 'authorization_manager')
    OR public.has_role(auth.uid(), 'authorization_coordinator')
    OR public.has_role(auth.uid(), 'scheduling')
    OR public.has_role(auth.uid(), 'scheduling_lead')
    OR public.has_role(auth.uid(), 'scheduling_coordinator')
    OR public.has_role(auth.uid(), 'staffing')
    OR public.has_role(auth.uid(), 'staffing_lead')
    OR public.has_role(auth.uid(), 'staffing_coordinator')
    OR public.has_role(auth.uid(), 'recruiting_assistant')
    OR public.has_role(auth.uid(), 'recruiting_lead')
    OR public.has_role(auth.uid(), 'recruiting_coordinator')
    OR public.has_role(auth.uid(), 'hr')
    OR public.has_role(auth.uid(), 'hr_admin')
    OR public.has_role(auth.uid(), 'hr_admin_assistant')
    OR public.has_role(auth.uid(), 'hr_manager')
    OR public.has_role(auth.uid(), 'hr_lead')
    OR public.has_role(auth.uid(), 'finance')
    OR public.has_role(auth.uid(), 'finance_benefits_lead')
    OR public.has_role(auth.uid(), 'finance_benefits_team')
    OR public.has_role(auth.uid(), 'billing_lead')
    OR public.has_role(auth.uid(), 'payroll_admin')
    OR public.has_role(auth.uid(), 'payroll_lead')
    OR public.has_role(auth.uid(), 'rcm_team')
    OR public.has_role(auth.uid(), 'qa')
    OR public.has_role(auth.uid(), 'qa_team')
    OR public.has_role(auth.uid(), 'qa_director')
    OR public.has_role(auth.uid(), 'qa_specialist')
    OR public.has_role(auth.uid(), 'clinical_director')
    OR public.has_role(auth.uid(), 'clinical_lead')
    OR public.has_role(auth.uid(), 'clinic_director')
    OR public.has_role(auth.uid(), 'bcba')
    OR public.has_role(auth.uid(), 'case_manager')
    OR public.has_role(auth.uid(), 'marketing')
    OR public.has_role(auth.uid(), 'marketing_team')
    OR public.has_role(auth.uid(), 'marketing_growth_lead')
    OR public.has_role(auth.uid(), 'business_development')
    OR public.has_role(auth.uid(), 'behavioral_support')
    OR public.has_role(auth.uid(), 'credentialing')
    OR public.has_role(auth.uid(), 'credentialing_team')
    OR public.has_role(auth.uid(), 'credentialing_lead')
    OR public.has_role(auth.uid(), 'credentialing_coordinator')
    OR public.has_role(auth.uid(), 'dept_manager')
    OR public.has_role(auth.uid(), 'clinic')
    OR public.has_role(auth.uid(), 'phone_support')
$$;
